const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sender', {
  getSettings:    ()                 => ipcRenderer.invoke('get-settings'),
  saveSettings:   (settings)         => ipcRenderer.invoke('save-settings', settings),
  sendDrop:       (payload)          => ipcRenderer.invoke('send-drop', payload),
  previewDrop:    (payload)          => ipcRenderer.invoke('preview-drop', payload),
  previewFacecamStart: ()            => ipcRenderer.invoke('preview-facecam-start'),
  previewFacecamStop: ()             => ipcRenderer.invoke('preview-facecam-stop'),
  chooseChaseAudio: ()               => ipcRenderer.invoke('choose-chase-audio'),
  chooseChaseSfxFolder: ()           => ipcRenderer.invoke('choose-chase-sfx-folder'),
  resolveLink:    (url)              => ipcRenderer.invoke('resolve-link', url),
  uploadAudio:    (buf)              => ipcRenderer.invoke('upload-audio', buf),
  uploadMedia:    (buf, mime)        => ipcRenderer.invoke('upload-media', { buffer: buf, mimeType: mime }),
  getUsers:       ()                 => ipcRenderer.invoke('get-users'),
  getFavorites:   ()                 => ipcRenderer.invoke('get-favorites'),
  saveFavorite:   (fav)              => ipcRenderer.invoke('save-favorite', fav),
  deleteFavorite: (id)               => ipcRenderer.invoke('delete-favorite', id),
  saveHistory:    (entry)            => ipcRenderer.send('save-history', entry),
  getHistory:     ()                 => ipcRenderer.invoke('get-history'),
  clearHistory:   ()                 => ipcRenderer.invoke('clear-history'),
  libraryList:    ()                 => ipcRenderer.invoke('library-list'),
  librarySave:    (payload)          => ipcRenderer.invoke('library-save', payload),
  librarySaveBuffer: (buffer, name, situation) => ipcRenderer.invoke('library-save-buffer', { buffer, name, situation }),
  libraryDelete:  (id)               => ipcRenderer.invoke('library-delete', id),
  libraryRename:  (id, name)         => ipcRenderer.invoke('library-rename', { id, name }),
  libraryUpload:  (id)               => ipcRenderer.invoke('library-upload', id),
  close:          ()                 => ipcRenderer.send('close-sender'),
  minimize:       ()                 => ipcRenderer.send('minimize-sender'),
  openSnipTool:   ()                 => ipcRenderer.invoke('open-snip-tool'),
  checkForUpdates:()                 => ipcRenderer.invoke('check-for-updates'),
  onUpdateStatus: (cb)               => ipcRenderer.on('update-status', (_e, msg) => cb(msg)),
  onShowTab:      (cb)               => ipcRenderer.on('show-tab',      (_e, tab) => cb(tab)),
  onSnipResult:   (cb)               => ipcRenderer.on('snip-result',   (_e, d)   => cb(d)),
  onFacecamStatus:(cb)               => ipcRenderer.on('facecam-status',(_e, d)   => cb(d)),
});
